deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    maxSurge: 1
    maxUnavailable: 0
  containers:
    - name: flaresolverr
      image: 
        repository: ghcr.io/flaresolverr/flaresolverr
        tag: latest
      ports:
        - name: http
          containerPort: 8191
      env:
        - name: LOG_LEVEL
          value: info
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
        limits:
          cpu: 4000m
          memory: 2000Mi

services:
  - name: service
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 8191